name: Generate and Commit CSV

on:
  push:  # Trigger on push events

jobs:
  generate_csv:
    runs-on: ubuntu-latest  # Run on Ubuntu runners

    steps:
      - uses: actions/checkout@v3  # Checkout code from GitHub

      - name: Run Python script
        run: python CSV_Generator.py

      - name: Add generated file
        run: git add .

      - name: Commit changes
        run: git commit -m "Add generated CSV file (automated)"

      - name: Push changes
        uses: actions/checkout@v3
        with:
          fetch-token: ${{ secrets.GITHUB_TOKEN }}  # Access token with push permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
