name: Run CSV Generator

on:
  schedule:
    - cron: '0 1 * * *'  # Adjust the cron expression as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any dependencies

      - name: Run CSV Generator
        run: python CSV_Generator.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output.csv  # Adjust the filename if needed
          git commit -m "Generated CSV"
          git push
